# Пользователи
## Создать нового пользователя

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Jack",
  "email": "torans@overlook3.net",
  "avatarUrl": "torrance.png",
  "password": "shining2",
  "accountType": "pro"
}

###

## Авторизовать пользователя

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook2.net",
  "password": "shining2"
}

###

## Отправить изображение

POST http://localhost:4000/users/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1ZTRkZWU2NGFhZjI4MDNhZjU2N2IyNSIsImVtYWlsIjoidG9yYW5zQG92ZXJsb29rMi5uZXQiLCJpYXQiOjE3MDk0OTgxMjIsImV4cCI6MTcwOTY3MDkyMn0.Bi6EtbThXlzhiwtllemFAb1dtWeVQv9r2RoejewENug

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< C:\Users\79817\Desktop\projects\2376891-six-cities-6\markup\img\avatar-angelina.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Проверить токен пользователя
GET http://localhost:4000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1ZTRkZWU2NGFhZjI4MDNhZjU2N2IyNSIsImVtYWlsIjoidG9yYW5zQG92ZXJsb29rMi5uZXQiLCJpYXQiOjE3MDk0OTgxMjIsImV4cCI6MTcwOTY3MDkyMn0.Bi6EtbThXlzhiwtllemFAb1dtWeVQv9r2RoejewENug
