# Получить объявление по идентификатору
GET http://localhost:4000/offers/65e2310e1ab2a66fac5158de HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1ZTRkZWU2NGFhZjI4MDNhZjU2N2IyNSIsImVtYWlsIjoidG9yYW5zQG92ZXJsb29rMi5uZXQiLCJpYXQiOjE3MDk0OTgxMjIsImV4cCI6MTcwOTY3MDkyMn0.Bi6EtbThXlzhiwtllemFAb1dtWeVQv9r2RoejewENug

###

GET http://localhost:4000/offers/65e2310e1ab2a66fac5158de HTTP/1.1

###

## Получить список объявлений
GET http://localhost:4000/offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1ZTRkZWU2NGFhZjI4MDNhZjU2N2IyNSIsImVtYWlsIjoidG9yYW5zQG92ZXJsb29rMi5uZXQiLCJpYXQiOjE3MDk0OTgxMjIsImV4cCI6MTcwOTY3MDkyMn0.Bi6EtbThXlzhiwtllemFAb1dtWeVQv9r2RoejewENug

###

GET http://localhost:4000/offers HTTP/1.1

###

## Получить определенное количество объявлений

GET http://localhost:4000/offers?limit=2 HTTP/1.1

###

## Получить список премиальных объявлений

GET http://localhost:4000/offers/Amsterdam/premium HTTP/1.1

###

GET http://localhost:4000/offers/Amsterdam/premium HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1ZTRkZWU2NGFhZjI4MDNhZjU2N2IyNSIsImVtYWlsIjoidG9yYW5zQG92ZXJsb29rMi5uZXQiLCJpYXQiOjE3MDk0OTgxMjIsImV4cCI6MTcwOTY3MDkyMn0.Bi6EtbThXlzhiwtllemFAb1dtWeVQv9r2RoejewENug

###

## Создать новое объявление

POST http://localhost:4000/offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1ZTRkZWU2NGFhZjI4MDNhZjU2N2IyNSIsImVtYWlsIjoidG9yYW5zQG92ZXJsb29rMi5uZXQiLCJpYXQiOjE3MDk0OTgxMjIsImV4cCI6MTcwOTY3MDkyMn0.Bi6EtbThXlzhiwtllemFAb1dtWeVQv9r2RoejewENug
Content-Type: application/json

{
  "title": "Waterfront",
  "description": "Design interior in most sympathetic area!",
  "date": "2023-09-26T09:23:20.316Z",
  "city": "Amsterdam",
  "previewImage": "https://14.react.pages.academy/static/offer/3.jpg",
  "images": [
    "https://14.react.pages.academy/static/offer/8.jpg",
    "https://14.react.pages.academy/static/offer/7.jpg",
    "https://14.react.pages.academy/static/offer/6.jpg",
    "https://14.react.pages.academy/static/offer/5.jpg",
    "https://14.react.pages.academy/static/offer/4.jpg",
    "https://14.react.pages.academy/static/offer/3.jpg"
    ],
  "isPremium": true,
  "isFavorite": true,
  "rating": 4.1,
  "offerType": "Apartment",
  "bedrooms": 1,
  "maxAdults": 4,
  "price": 1500,
  "goods": ["Breakfast", "Fridge"],
  "userId": "65e4dee64aaf2803af567b25",
  "commentCount": 0,
  "location": {"latitude": 48.85661, "longitude": 2.351499}
}

###

## Удалить объявление по идентификатору

DELETE http://localhost:4000/offers/65e67028522897cba9b50fbd HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1ZTRkZWU2NGFhZjI4MDNhZjU2N2IyNSIsImVtYWlsIjoidG9yYW5zQG92ZXJsb29rMi5uZXQiLCJpYXQiOjE3MDk0OTgxMjIsImV4cCI6MTcwOTY3MDkyMn0.Bi6EtbThXlzhiwtllemFAb1dtWeVQv9r2RoejewENug

###

## Обновить объявление

PATCH http://localhost:4000/offers/65e66b83221ab4c5d5843692 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1ZTRkZWU2NGFhZjI4MDNhZjU2N2IyNSIsImVtYWlsIjoidG9yYW5zQG92ZXJsb29rMi5uZXQiLCJpYXQiOjE3MDk0OTgxMjIsImV4cCI6MTcwOTY3MDkyMn0.Bi6EtbThXlzhiwtllemFAb1dtWeVQv9r2RoejewENug
Content-Type: application/json

{
  "price": 1100
}

###

## Получить список избранных объявлений
GET http://localhost:4000/offers/favorites HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1ZTRkZWU2NGFhZjI4MDNhZjU2N2IyNSIsImVtYWlsIjoidG9yYW5zQG92ZXJsb29rMi5uZXQiLCJpYXQiOjE3MDk0OTgxMjIsImV4cCI6MTcwOTY3MDkyMn0.Bi6EtbThXlzhiwtllemFAb1dtWeVQv9r2RoejewENug

###

## Добавить/удалить объявление в/из избранного
PATCH http://localhost:4000/offers/65e6a0d7e052f5e21290f43c/updateFavorites HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1ZTRkZWU2NGFhZjI4MDNhZjU2N2IyNSIsImVtYWlsIjoidG9yYW5zQG92ZXJsb29rMi5uZXQiLCJpYXQiOjE3MDk0OTgxMjIsImV4cCI6MTcwOTY3MDkyMn0.Bi6EtbThXlzhiwtllemFAb1dtWeVQv9r2RoejewENug

###
